Objetivo 0
pabloFernandezRR/IV-22-23 pull request #1
Opened 2022-09-30 09:20 UTC by pabloFernandezRR

Explicación de la primera idea de negocio

2022-09-30 12:09 UTC, JJ commented
Por favor, lee el guión que incluye que sigas la lista de comprobación y la pegues en el cuerpo del PR. Especialmente el último ítem no lo has hecho.

2022-09-30 12:10 UTC, JJ requested changes
por favor, lee el guión del objetivo 0 con atención para ver qué es lo que se requiere en este objetivo de la asignatura.

2022-10-06 07:16 UTC, pabloFernandezRR commented
@JJ listo para revisión

2022-10-06 10:21 UTC, pabloFernandezRR commented
@JJ nueva idea de proyecto

2022-10-06 18:42 UTC, JJ requested changes
Revisa bien el guión, por favor, sobre los problemas que se adaptan mejor a esta asignatura.

2022-10-06 18:42 UTC, JJ commented on README.md
> +En la actualidad un problema muy frecuente, es la complicación que tienen los padres de cuidar de sus hijos debido al gran número de horas de trabajo que se le exigen. Para ello suelen contratar una
Los problemas del mundo físico rara vez son adecuados para esta asignatura. Por favor, revisa los problemas aceptables en el guión.

2022-10-06 18:42 UTC, JJ commented on README.md
> +Este problema conduce al problema de la busqueda de una niñera, la cual se adecue con nuestros valores y preferencias.
Mira también lo que se dice con los problemas que se reducen a búsqueda, que se excluyen explícitamente.

2022-10-07 08:55 UTC, pabloFernandezRR commented
@JJ nueva idea

2022-10-07 15:10 UTC, JJ approved these changes
Antes de fusionarlo, por favor di qué es lo que hace que sea conveniente que esté en la nube.

2022-10-16 19:36 UTC, merged